name: GCC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gcc:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        gcc_version: [15]

    steps:
      - uses: actions/checkout@v6
  
      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_COMPILER=g++-${{ matrix.gcc_version }} \
            -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j $(nproc)

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure
